server:
  port: 8000

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        # Rota para procardio-api
        - id: procardio-api
          uri: http://localhost:8080
          predicates:
            - Path=/api/auth/**

        # Rota para notificacao-service
        - id: notificacao-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/notificacoes/**

        # Rota para llm-api
        - id: llm-api
          uri: http://localhost:8082
          predicates:
            - Path=/api/gemini/**
